### ISSUE TITLE
Can`t run

### ISSUE THREAD

**Issue by MaxKrskS** [agustinmista/PyAudioSelector#1]
$ /usr/local/bin/PyAudioSelector
Traceback (most recent call last):
  File "/usr/local/bin/PyAudioSelector", line 14, in <module>
    from gi.repository import AppIndicator
ImportError: cannot import name AppIndicator

**Comment by agustinmista** [comment]
Hi, I've got this problem in system with old ubuntu versions... What SO do you have?

try installing GI:
sudo apt-get install gir1.2-appindicator3-0.1
