### ISSUE TITLE
ubuntu 16.04

### ISSUE THREAD

**Issue by navaer** [agustinmista/PyAudioSelector#2]
Is it working in ubuntu 16.04?

**Comment by agustinmista** [comment]
I'm currently using it under Ubuntu 16.04. Are you having any trouble?

**Comment by navaer** [comment]
No errors on installation process, the icon isn't showing in the bar

**Comment by agustinmista** [comment]
Did you tried to run PyAudioSelector on the terminal? Can you paste the output? Sorry about the delayed  answer!
